name: test
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=3.0.0"

dependencies:
  collection: ^1.18.0
  equatable: ^2.0.0
  http: ^0.13.1
  intl: ^0.19.0

dev_dependencies:
  pedantic: ^1.11.0
